version: 2.1

jobs:
    build-binary:
        docker:
        -   image: golang:1.14
        working_directory: /tmp/cuckoo
        steps:
        -   checkout
        -   run: |
                export CGO_ENABLED=0 GOOS=linux
                mkdir build
                cd source
                go get github.com/markbates/pkger/cmd/pkger
                pkger
                go build -o ../build/cuckoo -tags netgo -ldflags '-extldflags "-static"'
                cd ..
                tar -czvf cuckoo.tar.gz build/
        -   store_artifacts:
                path: /tmp/cuckoo/cuckoo.tar.gz
                destination: cuckoo.tar.gz

    update-homebrew:
        docker:
        -   image: alpine/git:latest
        working_directory: /tmp/cuckoo
        steps:
        -   checkout
        -   run: |
                apt-get update && apt-get install -y gettext-base

                wget https://circle-artifacts.com/gh/borchero/cuckoo/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts/0/cuckoo.tar.gz
                export ARTIFACT_SHA256=$(cat cuckoo.tar.gz | sha256sum | cut -d' ' -f1)
                cd ..
                git clone git@github.com:borchero/homebrew-tools.git
                mkdir -p ./homebrew-tools/Formula
                envsubst < ./cuckoo/cuckoo.rb > ./homebrew-tools/Formula/cuckoo.rb

                cd homebrew-tools
                git config user.name "circleci"
                git config user.email "noreply@borchero.com"
                git add .
                git commit -m "Update Cuckoo"
                git push origin master

workflows:
    version: 2
    deploy-workflow:
        jobs:
        -   build-binary:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
        -   update-homebrew:
                requires:
                -   build-binary
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
