---
apiVersion: v1
kind: Config
preferences: {}
current-context: main

clusters:
-   name: cluster
    cluster:
        server: {{ .ClusterEndpoint }}
        certificate-authority-data: {{ .ClusterCA }}

users:
-   name: user
    user:
        auth-provider:
            name: gcp

contexts:
-   name: main
    context:
        cluster: cluster
        user: user
